#############################################################################
# Makefile for building: ProjectNotes3
# Generated by qmake (3.1) (Qt 5.15.6)
# Project:  ProjectNotes3.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile ProjectNotes3.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ProjectNotes31.0.0
DISTDIR = /home/paulmckinney/Documents/ProjectNotes3/.tmp/ProjectNotes31.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = actionitemprojectnotesmodel.cpp \
		actionitemsdetailsmeetingsmodel.cpp \
		clientslistview.cpp \
		clientsmodel.cpp \
		clientspage.cpp \
		columnview.cpp \
		comboboxdelegate.cpp \
		filterdatadialog.cpp \
		importexport.cpp \
		itemdetailsdelegate.cpp \
		itemdetailspage.cpp \
		itemdetailteamlistmodel.cpp \
		main.cpp \
		mainwindow.cpp \
		meetingattendeesmodel.cpp \
		meetingattendeesview.cpp \
		notesactionitemsmodel.cpp \
		notesactionitemsview.cpp \
		peoplelistview.cpp \
		peoplemodel.cpp \
		peoplepage.cpp \
		pnbasepage.cpp \
		pncheckboxdelegate.cpp \
		pncolumnmodel.cpp \
		pncomboboxdelegate.cpp \
		pndatabaseobjects.cpp \
		pndateeditdelegate.cpp \
		pndateeditex.cpp \
		pnlineeditfilebutton.cpp \
		pnlineeditfilebuttondelegate.cpp \
		pnsettings.cpp \
		pnsortfilterproxymodel.cpp \
		pnsqlquerymodel.cpp \
		pntableview.cpp \
		preferencesdialog.cpp \
		projectdetailsdelegate.cpp \
		projectdetailspage.cpp \
		projectlocationsmodel.cpp \
		projectlocationsview.cpp \
		projectnotesdelegate.cpp \
		projectnotesmodel.cpp \
		projectnotespage.cpp \
		projectnotesview.cpp \
		projectslistmodel.cpp \
		projectslistpage.cpp \
		projectslistview.cpp \
		projectsmodel.cpp \
		projectteammembersmodel.cpp \
		projectteammembersview.cpp \
		searchresultsmodel.cpp \
		statusreportitemsmodel.cpp \
		statusreportitemsview.cpp \
		teamsmodel.cpp \
		trackeritemcommentsmodel.cpp \
		trackeritemcommentsview.cpp \
		trackeritemsmodel.cpp \
		trackeritemsview.cpp \
		valueselectmodel.cpp \
		valuesview.cpp qrc_Resources.cpp \
		moc_comboboxdelegate.cpp \
		moc_filterdatadialog.cpp \
		moc_importexport.cpp \
		moc_itemdetailspage.cpp \
		moc_mainwindow.cpp \
		moc_pnbasepage.cpp \
		moc_pncheckboxdelegate.cpp \
		moc_pncomboboxdelegate.cpp \
		moc_pndatabaseobjects.cpp \
		moc_pndateeditdelegate.cpp \
		moc_pndateeditex.cpp \
		moc_pnlineeditfilebutton.cpp \
		moc_pnlineeditfilebuttondelegate.cpp \
		moc_pntableview.cpp \
		moc_preferencesdialog.cpp \
		moc_projectdetailspage.cpp \
		moc_projectnotespage.cpp
OBJECTS       = actionitemprojectnotesmodel.o \
		actionitemsdetailsmeetingsmodel.o \
		clientslistview.o \
		clientsmodel.o \
		clientspage.o \
		columnview.o \
		comboboxdelegate.o \
		filterdatadialog.o \
		importexport.o \
		itemdetailsdelegate.o \
		itemdetailspage.o \
		itemdetailteamlistmodel.o \
		main.o \
		mainwindow.o \
		meetingattendeesmodel.o \
		meetingattendeesview.o \
		notesactionitemsmodel.o \
		notesactionitemsview.o \
		peoplelistview.o \
		peoplemodel.o \
		peoplepage.o \
		pnbasepage.o \
		pncheckboxdelegate.o \
		pncolumnmodel.o \
		pncomboboxdelegate.o \
		pndatabaseobjects.o \
		pndateeditdelegate.o \
		pndateeditex.o \
		pnlineeditfilebutton.o \
		pnlineeditfilebuttondelegate.o \
		pnsettings.o \
		pnsortfilterproxymodel.o \
		pnsqlquerymodel.o \
		pntableview.o \
		preferencesdialog.o \
		projectdetailsdelegate.o \
		projectdetailspage.o \
		projectlocationsmodel.o \
		projectlocationsview.o \
		projectnotesdelegate.o \
		projectnotesmodel.o \
		projectnotespage.o \
		projectnotesview.o \
		projectslistmodel.o \
		projectslistpage.o \
		projectslistview.o \
		projectsmodel.o \
		projectteammembersmodel.o \
		projectteammembersview.o \
		searchresultsmodel.o \
		statusreportitemsmodel.o \
		statusreportitemsview.o \
		teamsmodel.o \
		trackeritemcommentsmodel.o \
		trackeritemcommentsview.o \
		trackeritemsmodel.o \
		trackeritemsview.o \
		valueselectmodel.o \
		valuesview.o \
		qrc_Resources.o \
		moc_comboboxdelegate.o \
		moc_filterdatadialog.o \
		moc_importexport.o \
		moc_itemdetailspage.o \
		moc_mainwindow.o \
		moc_pnbasepage.o \
		moc_pncheckboxdelegate.o \
		moc_pncomboboxdelegate.o \
		moc_pndatabaseobjects.o \
		moc_pndateeditdelegate.o \
		moc_pndateeditex.o \
		moc_pnlineeditfilebutton.o \
		moc_pnlineeditfilebuttondelegate.o \
		moc_pntableview.o \
		moc_preferencesdialog.o \
		moc_projectdetailspage.o \
		moc_projectnotespage.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		ProjectNotes3.pro actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		clientslistview.h \
		clientsmodel.h \
		clientspage.h \
		columnview.h \
		comboboxdelegate.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		importexport.h \
		itemdetailsdelegate.h \
		itemdetailspage.h \
		itemdetailteamlistmodel.h \
		mainwindow.h \
		meetingattendeesmodel.h \
		meetingattendeesview.h \
		notesactionitemsmodel.h \
		notesactionitemsview.h \
		peoplelistview.h \
		peoplemodel.h \
		peoplepage.h \
		pnbasepage.h \
		pncheckboxdelegate.h \
		pncolumnmodel.h \
		pncomboboxdelegate.h \
		pndatabaseobjects.h \
		pndateeditdelegate.h \
		pndateeditex.h \
		pnlineeditfilebutton.h \
		pnlineeditfilebuttondelegate.h \
		pnsettings.h \
		pnsortfilterproxymodel.h \
		pnsqlquerymodel.h \
		pntableview.h \
		preferencesdialog.h \
		projectdetailsdelegate.h \
		projectdetailspage.h \
		projectlocationsmodel.h \
		projectlocationsview.h \
		projectnotesdelegate.h \
		projectnotesmodel.h \
		projectnotespage.h \
		projectnotesview.h \
		projectslistmodel.h \
		projectslistpage.h \
		projectslistview.h \
		projectsmodel.h \
		projectteammembersmodel.h \
		projectteammembersview.h \
		searchresultsmodel.h \
		statusreportitemsmodel.h \
		statusreportitemsview.h \
		teamsmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemcommentsview.h \
		trackeritemsmodel.h \
		trackeritemsview.h \
		valueselectmodel.h \
		valuesview.h \
		widgets_export.h actionitemprojectnotesmodel.cpp \
		actionitemsdetailsmeetingsmodel.cpp \
		clientslistview.cpp \
		clientsmodel.cpp \
		clientspage.cpp \
		columnview.cpp \
		comboboxdelegate.cpp \
		filterdatadialog.cpp \
		importexport.cpp \
		itemdetailsdelegate.cpp \
		itemdetailspage.cpp \
		itemdetailteamlistmodel.cpp \
		main.cpp \
		mainwindow.cpp \
		meetingattendeesmodel.cpp \
		meetingattendeesview.cpp \
		notesactionitemsmodel.cpp \
		notesactionitemsview.cpp \
		peoplelistview.cpp \
		peoplemodel.cpp \
		peoplepage.cpp \
		pnbasepage.cpp \
		pncheckboxdelegate.cpp \
		pncolumnmodel.cpp \
		pncomboboxdelegate.cpp \
		pndatabaseobjects.cpp \
		pndateeditdelegate.cpp \
		pndateeditex.cpp \
		pnlineeditfilebutton.cpp \
		pnlineeditfilebuttondelegate.cpp \
		pnsettings.cpp \
		pnsortfilterproxymodel.cpp \
		pnsqlquerymodel.cpp \
		pntableview.cpp \
		preferencesdialog.cpp \
		projectdetailsdelegate.cpp \
		projectdetailspage.cpp \
		projectlocationsmodel.cpp \
		projectlocationsview.cpp \
		projectnotesdelegate.cpp \
		projectnotesmodel.cpp \
		projectnotespage.cpp \
		projectnotesview.cpp \
		projectslistmodel.cpp \
		projectslistpage.cpp \
		projectslistview.cpp \
		projectsmodel.cpp \
		projectteammembersmodel.cpp \
		projectteammembersview.cpp \
		searchresultsmodel.cpp \
		statusreportitemsmodel.cpp \
		statusreportitemsview.cpp \
		teamsmodel.cpp \
		trackeritemcommentsmodel.cpp \
		trackeritemcommentsview.cpp \
		trackeritemsmodel.cpp \
		trackeritemsview.cpp \
		valueselectmodel.cpp \
		valuesview.cpp
QMAKE_TARGET  = ProjectNotes3
DESTDIR       = 
TARGET        = ProjectNotes3


first: all
####### Build rules

ProjectNotes3:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ProjectNotes3.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		ProjectNotes3.pro \
		Resources.qrc
	$(QMAKE) -o Makefile ProjectNotes3.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
ProjectNotes3.pro:
Resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile ProjectNotes3.pro

qmake_all: FORCE


all: Makefile ProjectNotes3

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents Resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents actionitemprojectnotesmodel.h actionitemsdetailsmeetingsmodel.h clientslistview.h clientsmodel.h clientspage.h columnview.h comboboxdelegate.h filterdatadialog.h FilterSaveStructure.h importexport.h itemdetailsdelegate.h itemdetailspage.h itemdetailteamlistmodel.h mainwindow.h meetingattendeesmodel.h meetingattendeesview.h notesactionitemsmodel.h notesactionitemsview.h peoplelistview.h peoplemodel.h peoplepage.h pnbasepage.h pncheckboxdelegate.h pncolumnmodel.h pncomboboxdelegate.h pndatabaseobjects.h pndateeditdelegate.h pndateeditex.h pnlineeditfilebutton.h pnlineeditfilebuttondelegate.h pnsettings.h pnsortfilterproxymodel.h pnsqlquerymodel.h pntableview.h preferencesdialog.h projectdetailsdelegate.h projectdetailspage.h projectlocationsmodel.h projectlocationsview.h projectnotesdelegate.h projectnotesmodel.h projectnotespage.h projectnotesview.h projectslistmodel.h projectslistpage.h projectslistview.h projectsmodel.h projectteammembersmodel.h projectteammembersview.h searchresultsmodel.h statusreportitemsmodel.h statusreportitemsview.h teamsmodel.h trackeritemcommentsmodel.h trackeritemcommentsview.h trackeritemsmodel.h trackeritemsview.h valueselectmodel.h valuesview.h widgets_export.h $(DISTDIR)/
	$(COPY_FILE) --parents actionitemprojectnotesmodel.cpp actionitemsdetailsmeetingsmodel.cpp clientslistview.cpp clientsmodel.cpp clientspage.cpp columnview.cpp comboboxdelegate.cpp filterdatadialog.cpp importexport.cpp itemdetailsdelegate.cpp itemdetailspage.cpp itemdetailteamlistmodel.cpp main.cpp mainwindow.cpp meetingattendeesmodel.cpp meetingattendeesview.cpp notesactionitemsmodel.cpp notesactionitemsview.cpp peoplelistview.cpp peoplemodel.cpp peoplepage.cpp pnbasepage.cpp pncheckboxdelegate.cpp pncolumnmodel.cpp pncomboboxdelegate.cpp pndatabaseobjects.cpp pndateeditdelegate.cpp pndateeditex.cpp pnlineeditfilebutton.cpp pnlineeditfilebuttondelegate.cpp pnsettings.cpp pnsortfilterproxymodel.cpp pnsqlquerymodel.cpp pntableview.cpp preferencesdialog.cpp projectdetailsdelegate.cpp projectdetailspage.cpp projectlocationsmodel.cpp projectlocationsview.cpp projectnotesdelegate.cpp projectnotesmodel.cpp projectnotespage.cpp projectnotesview.cpp projectslistmodel.cpp projectslistpage.cpp projectslistview.cpp projectsmodel.cpp projectteammembersmodel.cpp projectteammembersview.cpp searchresultsmodel.cpp statusreportitemsmodel.cpp statusreportitemsview.cpp teamsmodel.cpp trackeritemcommentsmodel.cpp trackeritemcommentsview.cpp trackeritemsmodel.cpp trackeritemsview.cpp valueselectmodel.cpp valuesview.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_Resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_Resources.cpp
qrc_Resources.cpp: Resources.qrc \
		/usr/lib/qt5/bin/rcc \
		icons/people.png \
		icons/textunder.png \
		icons/editredo.png \
		icons/clients.png \
		icons/textjustify.png \
		icons/projects.png \
		icons/textleft.png \
		icons/delete.png \
		icons/copy.png \
		icons/textright.png \
		icons/add-on.png \
		icons/filter.png \
		icons/editpaste.png \
		icons/editundo.png \
		icons/editcut.png \
		icons/editcopy.png \
		icons/textcenter.png \
		icons/settings.png \
		icons/format-indent-more.png \
		icons/textbold.png \
		icons/format-indent-less.png \
		icons/textitalic.png \
		icons/new-record.png \
		icons/search.png \
		icons/back.png \
		icons/logo.png \
		icons/forward.png
	/usr/lib/qt5/bin/rcc -name Resources Resources.qrc -o qrc_Resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_comboboxdelegate.cpp moc_filterdatadialog.cpp moc_importexport.cpp moc_itemdetailspage.cpp moc_mainwindow.cpp moc_pnbasepage.cpp moc_pncheckboxdelegate.cpp moc_pncomboboxdelegate.cpp moc_pndatabaseobjects.cpp moc_pndateeditdelegate.cpp moc_pndateeditex.cpp moc_pnlineeditfilebutton.cpp moc_pnlineeditfilebuttondelegate.cpp moc_pntableview.cpp moc_preferencesdialog.cpp moc_projectdetailspage.cpp moc_projectnotespage.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_comboboxdelegate.cpp moc_filterdatadialog.cpp moc_importexport.cpp moc_itemdetailspage.cpp moc_mainwindow.cpp moc_pnbasepage.cpp moc_pncheckboxdelegate.cpp moc_pncomboboxdelegate.cpp moc_pndatabaseobjects.cpp moc_pndateeditdelegate.cpp moc_pndateeditex.cpp moc_pnlineeditfilebutton.cpp moc_pnlineeditfilebuttondelegate.cpp moc_pntableview.cpp moc_preferencesdialog.cpp moc_projectdetailspage.cpp moc_projectnotespage.cpp
moc_comboboxdelegate.cpp: comboboxdelegate.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paulmckinney/Documents/ProjectNotes3/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paulmckinney/Documents/ProjectNotes3 -I/home/paulmckinney/Documents/ProjectNotes3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include comboboxdelegate.h -o moc_comboboxdelegate.cpp

moc_filterdatadialog.cpp: filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		pnsqlquerymodel.h \
		valueselectmodel.h \
		pnsortfilterproxymodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paulmckinney/Documents/ProjectNotes3/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paulmckinney/Documents/ProjectNotes3 -I/home/paulmckinney/Documents/ProjectNotes3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include filterdatadialog.h -o moc_filterdatadialog.cpp

moc_importexport.cpp: importexport.h \
		pnsqlquerymodel.h \
		projectsmodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paulmckinney/Documents/ProjectNotes3/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paulmckinney/Documents/ProjectNotes3 -I/home/paulmckinney/Documents/ProjectNotes3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include importexport.h -o moc_importexport.cpp

moc_itemdetailspage.cpp: itemdetailspage.h \
		pnbasepage.h \
		pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		pnsqlquerymodel.h \
		valueselectmodel.h \
		pnsortfilterproxymodel.h \
		itemdetailsdelegate.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paulmckinney/Documents/ProjectNotes3/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paulmckinney/Documents/ProjectNotes3 -I/home/paulmckinney/Documents/ProjectNotes3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include itemdetailspage.h -o moc_itemdetailspage.cpp

moc_mainwindow.cpp: mainwindow.h \
		pndatabaseobjects.h \
		projectsmodel.h \
		pnsqlquerymodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h \
		pnsortfilterproxymodel.h \
		pnsettings.h \
		pnbasepage.h \
		pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		valueselectmodel.h \
		preferencesdialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paulmckinney/Documents/ProjectNotes3/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paulmckinney/Documents/ProjectNotes3 -I/home/paulmckinney/Documents/ProjectNotes3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_pnbasepage.cpp: pnbasepage.h \
		pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		pnsqlquerymodel.h \
		valueselectmodel.h \
		pnsortfilterproxymodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paulmckinney/Documents/ProjectNotes3/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paulmckinney/Documents/ProjectNotes3 -I/home/paulmckinney/Documents/ProjectNotes3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include pnbasepage.h -o moc_pnbasepage.cpp

moc_pncheckboxdelegate.cpp: pncheckboxdelegate.h \
		pnsqlquerymodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paulmckinney/Documents/ProjectNotes3/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paulmckinney/Documents/ProjectNotes3 -I/home/paulmckinney/Documents/ProjectNotes3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include pncheckboxdelegate.h -o moc_pncheckboxdelegate.cpp

moc_pncomboboxdelegate.cpp: pncomboboxdelegate.h \
		pnsqlquerymodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paulmckinney/Documents/ProjectNotes3/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paulmckinney/Documents/ProjectNotes3 -I/home/paulmckinney/Documents/ProjectNotes3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include pncomboboxdelegate.h -o moc_pncomboboxdelegate.cpp

moc_pndatabaseobjects.cpp: pndatabaseobjects.h \
		projectsmodel.h \
		pnsqlquerymodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h \
		pnsortfilterproxymodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paulmckinney/Documents/ProjectNotes3/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paulmckinney/Documents/ProjectNotes3 -I/home/paulmckinney/Documents/ProjectNotes3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include pndatabaseobjects.h -o moc_pndatabaseobjects.cpp

moc_pndateeditdelegate.cpp: pndateeditdelegate.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paulmckinney/Documents/ProjectNotes3/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paulmckinney/Documents/ProjectNotes3 -I/home/paulmckinney/Documents/ProjectNotes3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include pndateeditdelegate.h -o moc_pndateeditdelegate.cpp

moc_pndateeditex.cpp: pndateeditex.h \
		widgets_export.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paulmckinney/Documents/ProjectNotes3/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paulmckinney/Documents/ProjectNotes3 -I/home/paulmckinney/Documents/ProjectNotes3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include pndateeditex.h -o moc_pndateeditex.cpp

moc_pnlineeditfilebutton.cpp: pnlineeditfilebutton.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paulmckinney/Documents/ProjectNotes3/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paulmckinney/Documents/ProjectNotes3 -I/home/paulmckinney/Documents/ProjectNotes3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include pnlineeditfilebutton.h -o moc_pnlineeditfilebutton.cpp

moc_pnlineeditfilebuttondelegate.cpp: pnlineeditfilebuttondelegate.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paulmckinney/Documents/ProjectNotes3/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paulmckinney/Documents/ProjectNotes3 -I/home/paulmckinney/Documents/ProjectNotes3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include pnlineeditfilebuttondelegate.h -o moc_pnlineeditfilebuttondelegate.cpp

moc_pntableview.cpp: pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		pnsqlquerymodel.h \
		valueselectmodel.h \
		pnsortfilterproxymodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paulmckinney/Documents/ProjectNotes3/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paulmckinney/Documents/ProjectNotes3 -I/home/paulmckinney/Documents/ProjectNotes3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include pntableview.h -o moc_pntableview.cpp

moc_preferencesdialog.cpp: preferencesdialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paulmckinney/Documents/ProjectNotes3/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paulmckinney/Documents/ProjectNotes3 -I/home/paulmckinney/Documents/ProjectNotes3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include preferencesdialog.h -o moc_preferencesdialog.cpp

moc_projectdetailspage.cpp: projectdetailspage.h \
		pnbasepage.h \
		pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		pnsqlquerymodel.h \
		valueselectmodel.h \
		pnsortfilterproxymodel.h \
		projectdetailsdelegate.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paulmckinney/Documents/ProjectNotes3/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paulmckinney/Documents/ProjectNotes3 -I/home/paulmckinney/Documents/ProjectNotes3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include projectdetailspage.h -o moc_projectdetailspage.cpp

moc_projectnotespage.cpp: projectnotespage.h \
		pnbasepage.h \
		pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		pnsqlquerymodel.h \
		valueselectmodel.h \
		pnsortfilterproxymodel.h \
		projectnotesdelegate.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paulmckinney/Documents/ProjectNotes3/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paulmckinney/Documents/ProjectNotes3 -I/home/paulmckinney/Documents/ProjectNotes3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include projectnotespage.h -o moc_projectnotespage.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

actionitemprojectnotesmodel.o: actionitemprojectnotesmodel.cpp actionitemprojectnotesmodel.h \
		pnsqlquerymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o actionitemprojectnotesmodel.o actionitemprojectnotesmodel.cpp

actionitemsdetailsmeetingsmodel.o: actionitemsdetailsmeetingsmodel.cpp actionitemsdetailsmeetingsmodel.h \
		pnsqlquerymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o actionitemsdetailsmeetingsmodel.o actionitemsdetailsmeetingsmodel.cpp

clientslistview.o: clientslistview.cpp clientslistview.h \
		pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		pnsqlquerymodel.h \
		valueselectmodel.h \
		pnsortfilterproxymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clientslistview.o clientslistview.cpp

clientsmodel.o: clientsmodel.cpp clientsmodel.h \
		pnsqlquerymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clientsmodel.o clientsmodel.cpp

clientspage.o: clientspage.cpp clientspage.h \
		pnbasepage.h \
		pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		pnsqlquerymodel.h \
		valueselectmodel.h \
		pnsortfilterproxymodel.h \
		mainwindow.h \
		pndatabaseobjects.h \
		projectsmodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h \
		pnsettings.h \
		preferencesdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clientspage.o clientspage.cpp

columnview.o: columnview.cpp pnsqlquerymodel.h \
		columnview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		valueselectmodel.h \
		pnsortfilterproxymodel.h \
		pntableview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o columnview.o columnview.cpp

comboboxdelegate.o: comboboxdelegate.cpp comboboxdelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o comboboxdelegate.o comboboxdelegate.cpp

filterdatadialog.o: filterdatadialog.cpp filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		pnsqlquerymodel.h \
		valueselectmodel.h \
		pnsortfilterproxymodel.h \
		pnsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filterdatadialog.o filterdatadialog.cpp

importexport.o: importexport.cpp importexport.h \
		pnsqlquerymodel.h \
		projectsmodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		pndatabaseobjects.h \
		searchresultsmodel.h \
		pnsortfilterproxymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o importexport.o importexport.cpp

itemdetailsdelegate.o: itemdetailsdelegate.cpp itemdetailsdelegate.h \
		pnsqlquerymodel.h \
		pndateeditex.h \
		widgets_export.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o itemdetailsdelegate.o itemdetailsdelegate.cpp

itemdetailspage.o: itemdetailspage.cpp itemdetailspage.h \
		pnbasepage.h \
		pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		pnsqlquerymodel.h \
		valueselectmodel.h \
		pnsortfilterproxymodel.h \
		itemdetailsdelegate.h \
		pndatabaseobjects.h \
		projectsmodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o itemdetailspage.o itemdetailspage.cpp

itemdetailteamlistmodel.o: itemdetailteamlistmodel.cpp itemdetailteamlistmodel.h \
		pnsqlquerymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o itemdetailteamlistmodel.o itemdetailteamlistmodel.cpp

main.o: main.cpp mainwindow.h \
		pndatabaseobjects.h \
		projectsmodel.h \
		pnsqlquerymodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h \
		pnsortfilterproxymodel.h \
		pnsettings.h \
		pnbasepage.h \
		pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		valueselectmodel.h \
		preferencesdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		pndatabaseobjects.h \
		projectsmodel.h \
		pnsqlquerymodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h \
		pnsortfilterproxymodel.h \
		pnsettings.h \
		pnbasepage.h \
		pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		valueselectmodel.h \
		preferencesdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

meetingattendeesmodel.o: meetingattendeesmodel.cpp meetingattendeesmodel.h \
		pnsqlquerymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o meetingattendeesmodel.o meetingattendeesmodel.cpp

meetingattendeesview.o: meetingattendeesview.cpp meetingattendeesview.h \
		pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		pnsqlquerymodel.h \
		valueselectmodel.h \
		pnsortfilterproxymodel.h \
		pncomboboxdelegate.h \
		pncheckboxdelegate.h \
		pndatabaseobjects.h \
		projectsmodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o meetingattendeesview.o meetingattendeesview.cpp

notesactionitemsmodel.o: notesactionitemsmodel.cpp notesactionitemsmodel.h \
		pnsqlquerymodel.h \
		pnsettings.h \
		pndatabaseobjects.h \
		projectsmodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h \
		pnsortfilterproxymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o notesactionitemsmodel.o notesactionitemsmodel.cpp

notesactionitemsview.o: notesactionitemsview.cpp notesactionitemsview.h \
		pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		pnsqlquerymodel.h \
		valueselectmodel.h \
		pnsortfilterproxymodel.h \
		pncomboboxdelegate.h \
		pncheckboxdelegate.h \
		pndateeditdelegate.h \
		comboboxdelegate.h \
		pndatabaseobjects.h \
		projectsmodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o notesactionitemsview.o notesactionitemsview.cpp

peoplelistview.o: peoplelistview.cpp peoplelistview.h \
		pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		pnsqlquerymodel.h \
		valueselectmodel.h \
		pnsortfilterproxymodel.h \
		pncomboboxdelegate.h \
		pndatabaseobjects.h \
		projectsmodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o peoplelistview.o peoplelistview.cpp

peoplemodel.o: peoplemodel.cpp peoplemodel.h \
		pnsqlquerymodel.h \
		pndatabaseobjects.h \
		projectsmodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h \
		pnsortfilterproxymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o peoplemodel.o peoplemodel.cpp

peoplepage.o: peoplepage.cpp peoplepage.h \
		pnbasepage.h \
		pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		pnsqlquerymodel.h \
		valueselectmodel.h \
		pnsortfilterproxymodel.h \
		mainwindow.h \
		pndatabaseobjects.h \
		projectsmodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h \
		pnsettings.h \
		preferencesdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o peoplepage.o peoplepage.cpp

pnbasepage.o: pnbasepage.cpp pnbasepage.h \
		pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		pnsqlquerymodel.h \
		valueselectmodel.h \
		pnsortfilterproxymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pnbasepage.o pnbasepage.cpp

pncheckboxdelegate.o: pncheckboxdelegate.cpp pncheckboxdelegate.h \
		pnsqlquerymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pncheckboxdelegate.o pncheckboxdelegate.cpp

pncolumnmodel.o: pncolumnmodel.cpp pncolumnmodel.h \
		FilterSaveStructure.h \
		pnsqlquerymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pncolumnmodel.o pncolumnmodel.cpp

pncomboboxdelegate.o: pncomboboxdelegate.cpp pncomboboxdelegate.h \
		pnsqlquerymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pncomboboxdelegate.o pncomboboxdelegate.cpp

pndatabaseobjects.o: pndatabaseobjects.cpp pndatabaseobjects.h \
		projectsmodel.h \
		pnsqlquerymodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h \
		pnsortfilterproxymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pndatabaseobjects.o pndatabaseobjects.cpp

pndateeditdelegate.o: pndateeditdelegate.cpp pndateeditdelegate.h \
		pnsqlquerymodel.h \
		pndateeditex.h \
		widgets_export.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pndateeditdelegate.o pndateeditdelegate.cpp

pndateeditex.o: pndateeditex.cpp pndateeditex.h \
		widgets_export.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pndateeditex.o pndateeditex.cpp

pnlineeditfilebutton.o: pnlineeditfilebutton.cpp pnlineeditfilebutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pnlineeditfilebutton.o pnlineeditfilebutton.cpp

pnlineeditfilebuttondelegate.o: pnlineeditfilebuttondelegate.cpp pnlineeditfilebuttondelegate.h \
		pnlineeditfilebutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pnlineeditfilebuttondelegate.o pnlineeditfilebuttondelegate.cpp

pnsettings.o: pnsettings.cpp pnsettings.h \
		mainwindow.h \
		pndatabaseobjects.h \
		projectsmodel.h \
		pnsqlquerymodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h \
		pnsortfilterproxymodel.h \
		pnbasepage.h \
		pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		valueselectmodel.h \
		preferencesdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pnsettings.o pnsettings.cpp

pnsortfilterproxymodel.o: pnsortfilterproxymodel.cpp pnsortfilterproxymodel.h \
		pnsqlquerymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pnsortfilterproxymodel.o pnsortfilterproxymodel.cpp

pnsqlquerymodel.o: pnsqlquerymodel.cpp pnsqlquerymodel.h \
		pndatabaseobjects.h \
		projectsmodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h \
		pnsortfilterproxymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pnsqlquerymodel.o pnsqlquerymodel.cpp

pntableview.o: pntableview.cpp pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		pnsqlquerymodel.h \
		valueselectmodel.h \
		pnsortfilterproxymodel.h \
		pnsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pntableview.o pntableview.cpp

preferencesdialog.o: preferencesdialog.cpp preferencesdialog.h \
		pndatabaseobjects.h \
		projectsmodel.h \
		pnsqlquerymodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h \
		pnsortfilterproxymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preferencesdialog.o preferencesdialog.cpp

projectdetailsdelegate.o: projectdetailsdelegate.cpp projectdetailsdelegate.h \
		pnsqlquerymodel.h \
		pndateeditex.h \
		widgets_export.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectdetailsdelegate.o projectdetailsdelegate.cpp

projectdetailspage.o: projectdetailspage.cpp projectdetailspage.h \
		pnbasepage.h \
		pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		pnsqlquerymodel.h \
		valueselectmodel.h \
		pnsortfilterproxymodel.h \
		projectdetailsdelegate.h \
		pndatabaseobjects.h \
		projectsmodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectdetailspage.o projectdetailspage.cpp

projectlocationsmodel.o: projectlocationsmodel.cpp projectlocationsmodel.h \
		pnsqlquerymodel.h \
		pndatabaseobjects.h \
		projectsmodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h \
		pnsortfilterproxymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectlocationsmodel.o projectlocationsmodel.cpp

projectlocationsview.o: projectlocationsview.cpp projectlocationsview.h \
		pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		pnsqlquerymodel.h \
		valueselectmodel.h \
		pnsortfilterproxymodel.h \
		pnlineeditfilebuttondelegate.h \
		comboboxdelegate.h \
		pndatabaseobjects.h \
		projectsmodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectlocationsview.o projectlocationsview.cpp

projectnotesdelegate.o: projectnotesdelegate.cpp projectnotesdelegate.h \
		pnsqlquerymodel.h \
		pndateeditex.h \
		widgets_export.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectnotesdelegate.o projectnotesdelegate.cpp

projectnotesmodel.o: projectnotesmodel.cpp projectnotesmodel.h \
		pnsqlquerymodel.h \
		pndatabaseobjects.h \
		projectsmodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h \
		pnsortfilterproxymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectnotesmodel.o projectnotesmodel.cpp

projectnotespage.o: projectnotespage.cpp projectnotespage.h \
		pnbasepage.h \
		pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		pnsqlquerymodel.h \
		valueselectmodel.h \
		pnsortfilterproxymodel.h \
		projectnotesdelegate.h \
		pndatabaseobjects.h \
		projectsmodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h \
		trackeritemsview.h \
		pncomboboxdelegate.h \
		pncheckboxdelegate.h \
		pndateeditdelegate.h \
		comboboxdelegate.h \
		notesactionitemsview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectnotespage.o projectnotespage.cpp

projectnotesview.o: projectnotesview.cpp projectnotesview.h \
		pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		pnsqlquerymodel.h \
		valueselectmodel.h \
		pnsortfilterproxymodel.h \
		pndateeditdelegate.h \
		pncheckboxdelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectnotesview.o projectnotesview.cpp

projectslistmodel.o: projectslistmodel.cpp projectslistmodel.h \
		projectsmodel.h \
		pnsqlquerymodel.h \
		pndatabaseobjects.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h \
		pnsortfilterproxymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectslistmodel.o projectslistmodel.cpp

projectslistpage.o: projectslistpage.cpp projectslistpage.h \
		pnbasepage.h \
		pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		pnsqlquerymodel.h \
		valueselectmodel.h \
		pnsortfilterproxymodel.h \
		pndatabaseobjects.h \
		projectsmodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectslistpage.o projectslistpage.cpp

projectslistview.o: projectslistview.cpp projectslistview.h \
		pncomboboxdelegate.h \
		pnsqlquerymodel.h \
		pndateeditdelegate.h \
		comboboxdelegate.h \
		pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		valueselectmodel.h \
		pnsortfilterproxymodel.h \
		pndatabaseobjects.h \
		projectsmodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectslistview.o projectslistview.cpp

projectsmodel.o: projectsmodel.cpp projectsmodel.h \
		pnsqlquerymodel.h \
		pndatabaseobjects.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h \
		pnsortfilterproxymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectsmodel.o projectsmodel.cpp

projectteammembersmodel.o: projectteammembersmodel.cpp projectteammembersmodel.h \
		pnsqlquerymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectteammembersmodel.o projectteammembersmodel.cpp

projectteammembersview.o: projectteammembersview.cpp projectteammembersview.h \
		pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		pnsqlquerymodel.h \
		valueselectmodel.h \
		pnsortfilterproxymodel.h \
		pncomboboxdelegate.h \
		pncheckboxdelegate.h \
		pndatabaseobjects.h \
		projectsmodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectteammembersview.o projectteammembersview.cpp

searchresultsmodel.o: searchresultsmodel.cpp searchresultsmodel.h \
		pnsqlquerymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o searchresultsmodel.o searchresultsmodel.cpp

statusreportitemsmodel.o: statusreportitemsmodel.cpp statusreportitemsmodel.h \
		pnsqlquerymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o statusreportitemsmodel.o statusreportitemsmodel.cpp

statusreportitemsview.o: statusreportitemsview.cpp statusreportitemsview.h \
		comboboxdelegate.h \
		pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		pnsqlquerymodel.h \
		valueselectmodel.h \
		pnsortfilterproxymodel.h \
		pndatabaseobjects.h \
		projectsmodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o statusreportitemsview.o statusreportitemsview.cpp

teamsmodel.o: teamsmodel.cpp teamsmodel.h \
		pnsqlquerymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o teamsmodel.o teamsmodel.cpp

trackeritemcommentsmodel.o: trackeritemcommentsmodel.cpp trackeritemcommentsmodel.h \
		pnsqlquerymodel.h \
		pndatabaseobjects.h \
		projectsmodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h \
		pnsortfilterproxymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o trackeritemcommentsmodel.o trackeritemcommentsmodel.cpp

trackeritemcommentsview.o: trackeritemcommentsview.cpp trackeritemcommentsview.h \
		pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		pnsqlquerymodel.h \
		valueselectmodel.h \
		pnsortfilterproxymodel.h \
		pndateeditdelegate.h \
		pncomboboxdelegate.h \
		pndatabaseobjects.h \
		projectsmodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o trackeritemcommentsview.o trackeritemcommentsview.cpp

trackeritemsmodel.o: trackeritemsmodel.cpp trackeritemsmodel.h \
		pnsqlquerymodel.h \
		pndatabaseobjects.h \
		projectsmodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		searchresultsmodel.h \
		pnsortfilterproxymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o trackeritemsmodel.o trackeritemsmodel.cpp

trackeritemsview.o: trackeritemsview.cpp trackeritemsview.h \
		pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		pnsqlquerymodel.h \
		valueselectmodel.h \
		pnsortfilterproxymodel.h \
		pncomboboxdelegate.h \
		pncheckboxdelegate.h \
		pndateeditdelegate.h \
		comboboxdelegate.h \
		pndatabaseobjects.h \
		projectsmodel.h \
		projectslistmodel.h \
		clientsmodel.h \
		peoplemodel.h \
		teamsmodel.h \
		statusreportitemsmodel.h \
		projectteammembersmodel.h \
		projectlocationsmodel.h \
		projectnotesmodel.h \
		actionitemprojectnotesmodel.h \
		actionitemsdetailsmeetingsmodel.h \
		meetingattendeesmodel.h \
		notesactionitemsmodel.h \
		itemdetailteamlistmodel.h \
		trackeritemcommentsmodel.h \
		trackeritemsmodel.h \
		searchresultsmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o trackeritemsview.o trackeritemsview.cpp

valueselectmodel.o: valueselectmodel.cpp valueselectmodel.h \
		pnsqlquerymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o valueselectmodel.o valueselectmodel.cpp

valuesview.o: valuesview.cpp valuesview.h \
		pntableview.h \
		filterdatadialog.h \
		FilterSaveStructure.h \
		pncolumnmodel.h \
		pnsqlquerymodel.h \
		valueselectmodel.h \
		pnsortfilterproxymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o valuesview.o valuesview.cpp

qrc_Resources.o: qrc_Resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Resources.o qrc_Resources.cpp

moc_comboboxdelegate.o: moc_comboboxdelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_comboboxdelegate.o moc_comboboxdelegate.cpp

moc_filterdatadialog.o: moc_filterdatadialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filterdatadialog.o moc_filterdatadialog.cpp

moc_importexport.o: moc_importexport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_importexport.o moc_importexport.cpp

moc_itemdetailspage.o: moc_itemdetailspage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_itemdetailspage.o moc_itemdetailspage.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_pnbasepage.o: moc_pnbasepage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pnbasepage.o moc_pnbasepage.cpp

moc_pncheckboxdelegate.o: moc_pncheckboxdelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pncheckboxdelegate.o moc_pncheckboxdelegate.cpp

moc_pncomboboxdelegate.o: moc_pncomboboxdelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pncomboboxdelegate.o moc_pncomboboxdelegate.cpp

moc_pndatabaseobjects.o: moc_pndatabaseobjects.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pndatabaseobjects.o moc_pndatabaseobjects.cpp

moc_pndateeditdelegate.o: moc_pndateeditdelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pndateeditdelegate.o moc_pndateeditdelegate.cpp

moc_pndateeditex.o: moc_pndateeditex.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pndateeditex.o moc_pndateeditex.cpp

moc_pnlineeditfilebutton.o: moc_pnlineeditfilebutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pnlineeditfilebutton.o moc_pnlineeditfilebutton.cpp

moc_pnlineeditfilebuttondelegate.o: moc_pnlineeditfilebuttondelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pnlineeditfilebuttondelegate.o moc_pnlineeditfilebuttondelegate.cpp

moc_pntableview.o: moc_pntableview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pntableview.o moc_pntableview.cpp

moc_preferencesdialog.o: moc_preferencesdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_preferencesdialog.o moc_preferencesdialog.cpp

moc_projectdetailspage.o: moc_projectdetailspage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_projectdetailspage.o moc_projectdetailspage.cpp

moc_projectnotespage.o: moc_projectnotespage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_projectnotespage.o moc_projectnotespage.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

