site_name: Project Notes Documentation

theme:
  name: readthedocs
  highlightjs: true

nav:
  - 'Home': index.md
  - 'Introduction':
    - 'Getting Started': Introduction/GettingStarted.md
    - 'System Requirements': Introduction/SystemRequirements.md
  - 'Interface Overview':
    - 'File Menu': InterfaceOverview/FileMenu.md
    - 'Edit Menu': InterfaceOverview/EditMenu.md
    - 'Plugins Menu': InterfaceOverview/PluginsMenu.md
    - 'View Menu': InterfaceOverview/ViewMenu.md
    - 'History Menu': InterfaceOverview/HistoryMenu.md
    - 'Toolbar': InterfaceOverview/Toolbar.md
    - 'Preferences': InterfaceOverview/Preferences.md
    - 'Project List Page': InterfaceOverview/ProjectListPage.md
    - 'Project Page': InterfaceOverview/ProjectPage.md
    - 'Notes Page': InterfaceOverview/NotesPage.md
    - 'Item Tracker Page': InterfaceOverview/ItemTrackerPage.md
    - 'Action Item Detail Page': InterfaceOverview/ActionItemDetailPage.md
    - 'People List Page': InterfaceOverview/PeopleListPage.md
    - 'Client List Page': InterfaceOverview/ClientListPage.md
    - 'Search Page': InterfaceOverview/SearchPage.md
    - 'Filter Tool': InterfaceOverview/FilterTool.md
    - 'Sorting and Sizing Columns': InterfaceOverview/SortingandSizingColumns.md
    - 'Earned Value Terms': InterfaceOverview/EarnedValueTerms.md
    - 'Presenting to Clients': InterfaceOverview/PresentingToClients.md
  - 'Plugins Overview':
    - 'Adding Functionality': PluginsOverview/AddingFunctionality.md
    - 'Data Types': PluginsOverview/DataTypes.md
    - 'Project Notes XML': PluginsOverview/ProjectNotesXML.md
  - 'Standard Plugins':
    - 'Plugin Settings': StandardPlugins/PluginSettings.md
    - 'Outlook Integration': StandardPlugins/OutlookIntegration.md
    - 'File Finder': StandardPlugins/FileFinder.md
    - 'My Shortcuts': StandardPlugins/MyShortcuts.md
    - 'Team Member Quick Add': StandardPlugins/TeamMemberQuickAdd.md
    - 'Export Meeting Notes': StandardPlugins/ExportMeetingNotes.md
    - 'Meeting Notes Archive': StandardPlugins/MeetingNotesArchive.md
    - 'Export Tracker Items': StandardPlugins/ExportTrackerItems.md
    - 'Tracker Report Generation': StandardPlugins/TrackerReportGeneration.md
    - 'New Document Templates': StandardPlugins/NewDocumentTemplates.md
    - 'Send Meeting Notes': StandardPlugins/SendMeetingNotes.md
    - 'Send Project Emails': StandardPlugins/SendProjectEmails.md
    - 'Project Email Archive': StandardPlugins/ProjectEmailArchive.md
    - 'Schedule an Internal Status Meeting': StandardPlugins/ScheduleanInternalStatusMeeting.md
    - 'Schedule a Customer Status Meeting': StandardPlugins/ScheduleaCustomerStatusMeeting.md
    - 'Schedule an Internal Kickoff Meeting': StandardPlugins/ScheduleanInternalKickoffMeeting.md
    - 'Schedule a Customer Kickoff Meeting': StandardPlugins/ScheduleaCustomerKickoffMeeting.md
    - 'Schedule an Internal Lessons Learned Meeting': StandardPlugins/ScheduleanInternalLessonsLearned.md
    - 'Schedule a Customer Lessons Learned Meeting': StandardPlugins/ScheduleaCustomerLessonsLearned.md
    - 'IFS Cloud Integration': StandardPlugins/IFSCloud.md
    - 'Editor': StandardPlugins/Editor.md

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - def_list
