site_name: Project Notes Documentation
theme:
  name: readthedocs
  highlightjs: true
#plugins:
#  - search
#  - mkdocstrings:
#      handlers:
#        # See: https://mkdocstrings.github.io/python/usage/
#        python:
#          options:
#            docstring_style: sphinx
markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - def_list
#  - markdown_include.include:
#      base_path: .
#  - admonition
