#include "StatusReportBuilder.h"
#include <QPageSize>
#include <QRegularExpression>
#include <algorithm>
namespace PN::Comm { namespace {
QString e(const QString&s){return s.toHtmlEscaped();}
QString activity(const QString&t,const QStringList&items){return "<div class='activity-title'>"+e(t)+"</div><div class='activity-box'>"+e(items.join("\n")).replace("\n","<br>")+"</div>";}
int priority(const QString&s){if(s=="High")return 0;if(s=="Medium")return 1;if(s=="Low")return 2;return 3;}
}
std::optional<ReportDocument> StatusReportBuilder::build(const StatusReportInput &in,ValidationResult *validation){
 if(!in.reportingDate.isValid()){if(validation)validation->addError("reporting-date-required","reportingDate");return{};}
 const auto dates=reviewPeriodDates(in.reportingPeriod,in.reportingDate);const auto ev=earnedValueMetrics(in.budget,in.actual,in.bcwp,in.bcws,in.bac);QList<StatusIssue> issues;QString rows;
 for(const auto&i:in.issues)if(in.internalReport||!i.internal)issues.append(i);
 std::stable_sort(issues.begin(),issues.end(),[](const auto&a,const auto&b){if(priority(a.priority)!=priority(b.priority))return priority(a.priority)<priority(b.priority);const auto ad=QDate::fromString(a.dueDate,"MM/dd/yyyy"),bd=QDate::fromString(b.dueDate,"MM/dd/yyyy");if(ad.isValid()!=bd.isValid())return ad.isValid();if(ad.isValid()&&ad!=bd)return ad>bd;return false;});
 for(const auto&i:issues)rows+="<tr><td>"+e(i.name)+"</td><td>"+e(i.assignedTo)+"</td><td class='priority-"+e(i.priority.toLower())+"'>"+e(i.priority)+"</td><td>"+e(i.dueDate)+"</td><td>"+e(i.status)+"</td></tr>";
 const QString date=in.reportingDate.toString("MM/dd/yyyy");QString fragment="<h1>Project Status Report</h1><table class='header'><tr><th>Project Manager:</th><td>"+e(in.managerName)+"</td><th>Date:</th><td>"+e(date)+"</td></tr><tr><th>Stakeholders:</th><td>"+e(in.stakeholders.join(", "))+"</td><th>Review Period:</th><td>"+e(dates.first.isEmpty()?QString():dates.first+" to "+dates.second)+"</td></tr><tr><th>Description:</th><td>"+e(in.projectName)+"</td><th>Project #:</th><td>"+e(in.projectNumber)+"</td></tr></table>"+activity("Activities in Progress",in.activitiesInProgress)+activity("Activities For Next Period",in.activitiesNextPeriod)+activity("Activities Completed",in.activitiesCompleted)+"<h2>Issues</h2><table class='issues'><tr><th>Issue Items</th><th>Assigned To</th><th>Priority</th><th>Due Date</th><th>Status</th></tr>"+rows+"</table><h2>Earned Value Project Metrics</h2><table class='metrics'><tr><th>BCWP</th><td>"+e(ev.bcwp)+"</td><th>BCWS</th><td>"+e(ev.bcws)+"</td></tr><tr><th>BAC</th><td>"+e(ev.bac)+"</td><th>Actual</th><td>"+e(ev.actual)+"</td></tr><tr><th>EAC</th><td>"+e(ev.eac)+"</td><th>CPI</th><td>"+e(ev.cpi)+"</td></tr><tr><th>CV</th><td>"+e(ev.cv)+"</td><th>SV</th><td>"+e(ev.sv)+"</td></tr><tr><th>Percent Work Complete</th><td colspan='3'>"+e(ev.pctComplete)+"</td></tr></table><p class='footer'>Report Date: "+e(date)+"</p><p class='branding'>Created by Project Notes (<a href='https://www.projectnotespro.com'>www.projectnotespro.com</a>)</p>";
 ReportDocument r;r.workflow=Workflow::StatusReport;r.emailFragment=fragment;r.htmlDocument="<!doctype html><html><head><meta charset='utf-8'><style>body{font-family:Calibri,Arial,sans-serif;font-size:10pt;padding:.2in}h1{color:#fff;background:#1F497D;padding:6px}h2,.activity-title{color:#1F497D;border-bottom:3px solid #1F497D}.activity-box{background:#DCE6F1;border:1px solid #808080;padding:6px;white-space:pre-wrap}table{border-collapse:collapse;width:100%;margin:4px 0}th,td{border:1px solid #808080;padding:3px 6px;vertical-align:top}th{background:#EEECE1}.priority-high{color:#C00000;font-weight:bold}.footer{margin-top:8px;font-size:8pt;color:#666}.branding{font-size:9pt;color:#000;margin-top:2px}.branding a{color:#0066CC;text-decoration:none}</style></head><body>"+fragment+"</body></html>";QString plain=fragment;plain.remove(QRegularExpression("<[^>]*>"));r.plainText=plain.simplified();r.defaultSubject=in.projectNumber+" "+in.projectName+" - Status Report "+date;r.fileStem=in.projectNumber+" Status Report"+(in.internalReport?" Internal":"");r.pdfLayout=QPageLayout(QPageSize(QPageSize::Letter),QPageLayout::Portrait,QMarginsF(20,20,20,20),QPageLayout::Millimeter);return r;
}
}
