#include "StatusReportBuilder.h"

#include <QPageSize>
#include <QRegularExpression>
#include <algorithm>

namespace PN::Comm {
namespace {
QString e(const QString &s) { return s.toHtmlEscaped(); }
int rank(const QString &s) { return s == "High" ? 0 : s == "Medium" ? 1 : s == "Low" ? 2 : 3; }
QString activity(const QString &title, const QStringList &items) {
    return "<div class='activity-title'>" + e(title) + "</div><div class='activity-box'>"
        + e(items.join("\n")).replace("\n", "<br>") + "</div>";
}
const char appendix[] = R"HTML(<div class="section-title">Appendix</div><table class="appendix-table"><tr><td colspan="2" class="appendix-title-cell">Earned Value Project Management Terms</td></tr><tr><td class="cell-label">BCWP</td><td class="cell-value">The approved budget for the work actually completed by the specified date; also referred to as the budgeted cost of work performed (BCWP) or Earned Value. Travel costs are not included in calculations.</td></tr><tr><td class="cell-label">BCWS</td><td class="cell-value">The approved budget for the work scheduled to be completed by a specified date; also referred to as the budgeted cost of work scheduled (BCWS) and Planned Value (PV). Travel costs are not included in calculations.</td></tr><tr><td class="cell-label">Budget At Completion</td><td class="cell-value">The total Planned Value (PV or BCWS) at the end of the project. If a project has a Management Reserve (MR), it is typically not included in the Budget At Completion (BAC).</td></tr><tr><td class="cell-label">Estimate At Completion</td><td class="cell-value">The most likely estimate of what the project will cost, taking into account both current schedule performance and budget performance. Travel costs are not included in calculations.<div class="formula-block">Actual&nbsp;Cost&nbsp;+&nbsp;<span class="fraction"><span class="num">(Budget&nbsp;At&nbsp;Completion&nbsp;&minus;&nbsp;Earned&nbsp;Value)</span><span class="den"><span class="fraction"><span class="num">Earned&nbsp;Value</span><span class="den">Actual&nbsp;Cost</span></span>&nbsp;&times;&nbsp;<span class="fraction"><span class="num">Earned&nbsp;Value</span><span class="den">Planned&nbsp;Value</span></span></span></span></div></td></tr><tr><td class="cell-label">Cost Variance</td><td class="cell-value">The percentage difference between the Earned Value and Actual Cost. A negative number indicates the project is running under budget as of the status date.</td></tr><tr><td class="cell-label">Schedule Variance</td><td class="cell-value">The percentage difference between the Earned Value and the Planned Value. A positive number indicates the project is running ahead of schedule as of the status date.</td></tr><tr><td class="cell-label">Percent Work Complete</td><td class="cell-value">The percent of Earned Value compared to Budget At Completion. If greater than the Percentage of Budget Consumed, it is a good indication the project is running under budget.</td></tr></table>)HTML";
const char styles[] = R"CSS(body{font-family:Calibri,Arial,sans-serif;font-size:10pt;margin:0;padding:.2in}h1{font-size:15pt;color:#fff;background:#1F497D;font-weight:bold;margin:0 0 8px;padding:6px 8px}table.header-table{border-collapse:collapse;width:100%;margin-bottom:10px}table.header-table td{border:1px solid #808080;padding:3px 6px;font-size:10pt;vertical-align:top}.cell-label{background:#EEECE1;font-weight:bold;width:110px}.cell-value{background:#fff}.section-title{font-size:10pt;font-weight:bold;color:#1F497D;text-transform:uppercase;margin-top:10px;padding-bottom:3px;border-bottom:3px solid #1F497D}.activity-title{font-size:10pt;font-weight:bold;color:#1F497D;text-transform:uppercase;margin-top:10px}.activity-box{background:#DCE6F1;border:1px solid #808080;min-height:40px;padding:6px;font-size:10pt;white-space:pre-wrap}table.issues-table{border-collapse:collapse;width:100%;table-layout:fixed;margin-top:4px}table.issues-table th{background:#EEECE1;border:1px solid #808080;padding:3px 6px;text-align:center;font-size:9pt;font-weight:bold}table.issues-table td{background:#fff;border:1px solid #808080;padding:3px 6px;vertical-align:top;font-size:9pt;word-wrap:break-word;white-space:pre-wrap}.col-item{width:40%}.col-assigned{width:20%;text-align:center}.col-priority{width:12%;text-align:center}.col-duedate{width:14%;text-align:center}.col-status{width:14%;text-align:center}.priority-high{color:#C00000;font-weight:bold}.priority-medium{color:#9C6500;font-weight:bold}.priority-low{color:#375623;font-weight:bold}.ev-columns{display:flex;gap:12px;margin-top:4px;align-items:flex-start}table.ev-table{border-collapse:collapse;flex:1;width:50%}table.ev-table td{border:1px solid #808080;padding:3px 6px;font-size:9pt;vertical-align:top}table.ev-table .cell-label{width:60%}table.appendix-table{border-collapse:collapse;width:100%;margin-top:4px;margin-bottom:10px}table.appendix-table td{border:1px solid #808080;padding:3px 6px;font-size:8.5pt;vertical-align:top}table.appendix-table .cell-label{width:15%}.appendix-title-cell{background:#EEECE1;font-weight:bold;font-size:9.5pt}.formula-block{text-align:center;margin:6px 0 4px;font-family:"Cambria Math",Cambria,Georgia,serif;font-style:italic;font-size:10.5pt}.fraction{display:inline-flex;flex-direction:column;vertical-align:middle;text-align:center;margin:0 3px}.fraction .num{padding:0 4px 2px;border-bottom:1px solid #000}.fraction .den{padding:2px 4px 0;display:inline-flex;align-items:center;justify-content:center}.footer{margin-top:8px;font-size:8pt;color:#666}.branding{font-size:9pt;color:#000;margin-top:2px}.branding a{color:#0066CC;text-decoration:none}.branding a:hover{text-decoration:underline})CSS";
}

std::optional<ReportDocument> StatusReportBuilder::build(const StatusReportInput &in, ValidationResult *validation)
{
    if (!in.reportingDate.isValid()) { if (validation) validation->addError("reporting-date-required", "reportingDate"); return {}; }
    const auto dates = reviewPeriodDates(in.reportingPeriod, in.reportingDate);
    const auto ev = earnedValueMetrics(in.budget, in.actual, in.bcwp, in.bcws, in.bac);
    QList<StatusIssue> issues;
    for (const auto &issue : in.issues) if (in.internalReport || !issue.internal) issues.append(issue);
    std::stable_sort(issues.begin(), issues.end(), [](const auto &a, const auto &b) {
        if (rank(a.priority) != rank(b.priority)) return rank(a.priority) < rank(b.priority);
        const auto ad = QDate::fromString(a.dueDate, "MM/dd/yyyy"), bd = QDate::fromString(b.dueDate, "MM/dd/yyyy");
        if (ad.isValid() != bd.isValid()) return ad.isValid(); return ad.isValid() && ad != bd ? ad > bd : false;
    });
    QString rows;
    for (const auto &issue : issues) {
        const QString cls = issue.priority == "High" ? "priority-high" : issue.priority == "Medium" ? "priority-medium" : "priority-low";
        rows += "<tr><td class='col-item'>" + e(issue.name) + "</td><td class='col-assigned'>" + e(issue.assignedTo) + "</td><td class='col-priority'><span class='" + cls + "'>" + e(issue.priority) + "</span></td><td class='col-duedate'>" + e(issue.dueDate) + "</td><td class='col-status'>" + e(issue.status) + "</td></tr>";
    }
    const QString date = in.reportingDate.toString("MM/dd/yyyy"), review = dates.first.isEmpty() ? QString() : dates.first + " to " + dates.second;
    const QString metricRows = "<tr><td class='cell-label'>Budgeted Cost of Work Performed</td><td class='cell-value'>" + e(ev.bcwp) + "</td></tr><tr><td class='cell-label'>Budgeted Cost of Work Scheduled</td><td class='cell-value'>" + e(ev.bcws) + "</td></tr><tr><td class='cell-label'>Budget At Completion</td><td class='cell-value'>" + e(ev.bac) + "</td></tr><tr><td class='cell-label'>Actual Costs</td><td class='cell-value'>" + e(ev.actual) + "</td></tr><tr><td class='cell-label'>Estimate At Completion</td><td class='cell-value'>" + e(ev.eac) + "</td></tr><tr><td class='cell-label'>Cost Variance</td><td class='cell-value'>" + e(ev.cv) + "</td></tr><tr><td class='cell-label'>Schedule Variance</td><td class='cell-value'>" + e(ev.sv) + "</td></tr><tr><td class='cell-label'>Percent Work Complete</td><td class='cell-value'>" + e(ev.pctComplete) + "</td></tr><tr><td class='cell-label'>CPI</td><td class='cell-value'>" + e(ev.cpi) + "</td></tr>";
    const QString metrics = "<div class='section-title'>Earned Value Project Metrics</div><div class='ev-columns'><table class='ev-table'><tr><td class='cell-label'>Reporting Period</td><td class='cell-value'>" + e(in.reportingPeriod) + "</td></tr><tr><td class='cell-label'>Starting Date</td><td class='cell-value'>" + e(dates.first) + "</td></tr><tr><td class='cell-label'>Ending Date</td><td class='cell-value'>" + e(dates.second) + "</td></tr></table><table class='ev-table'>" + metricRows + "</table></div>";
    const QString fragment = "<h1>Project Status Report</h1><table class='header-table'><tr><td class='cell-label'>Project Manager:</td><td class='cell-value'>" + e(in.managerName) + "</td><td class='cell-label'>Date:</td><td class='cell-value'>" + e(date) + "</td></tr><tr><td class='cell-label'>Stakeholders:</td><td class='cell-value'>" + e(in.stakeholders.join(", ")) + "</td><td class='cell-label'>Review Period:</td><td class='cell-value'>" + e(review) + "</td></tr><tr><td class='cell-label'>Description:</td><td class='cell-value'>" + e(in.projectName) + "</td><td class='cell-label'>Project #:</td><td class='cell-value'>" + e(in.projectNumber) + "</td></tr></table>" + activity("Activities in Progress", in.activitiesInProgress) + activity("Activities For Next Period", in.activitiesNextPeriod) + activity("Activities Completed", in.activitiesCompleted) + "<div class='section-title'>Issues</div><table class='issues-table'><thead><tr><th class='col-item'>Issue Items</th><th class='col-assigned'>Assigned To</th><th class='col-priority'>Priority</th><th class='col-duedate'>Due Date</th><th class='col-status'>Status</th></tr></thead><tbody>" + rows + "</tbody></table>" + metrics + appendix + "<p class='footer'>Report Date: " + e(date) + "</p><p class='branding'>Created by Project Notes (<a href='https://www.projectnotespro.com'>www.projectnotespro.com</a>)</p>";
    ReportDocument report; report.workflow = Workflow::StatusReport; report.emailFragment = fragment;
    report.htmlDocument = "<!DOCTYPE html><html><head><meta charset='utf-8'><meta name='viewport' content='width=780'><style>" + QString::fromLatin1(styles) + "</style></head><body>" + fragment + "</body></html>";
    QString plain = fragment; plain.remove(QRegularExpression("<[^>]*>")); report.plainText = plain.simplified();
    report.defaultSubject = in.projectNumber + " " + in.projectName + " - Status Report " + date;
    report.fileStem = in.projectNumber + " Status Report" + (in.internalReport ? " Internal" : "");
    report.pdfLayout = QPageLayout(QPageSize(QPageSize::Letter), QPageLayout::Portrait, QMarginsF(20, 20, 20, 20), QPageLayout::Millimeter);
    return report;
}
} // namespace PN::Comm
