#include "TrackerItemsReportBuilder.h"
#include <QPageSize>
#include <QRegularExpression>
#include <algorithm>
namespace PN::Comm { namespace {
QString e(const QString&s){return s.toHtmlEscaped();}
int priority(const QString&s){if(s=="High")return 0;if(s=="Medium")return 1;if(s=="Low")return 2;return 3;}
int status(const QString&s){static const QStringList order{"New","Assigned","Resolved","Defered","Cancelled"};auto i=order.indexOf(s);return i<0?order.size():i;}
}
std::optional<ReportDocument> TrackerItemsReportBuilder::build(const TrackerItemsReportInput &in,ValidationResult *validation){
 if(!in.options.tracker){if(validation)validation->addError("tracker-filters-required","tracker");return{};}const auto &f=*in.options.tracker;QList<TrackerReportItem>items;
 for(const auto&i:in.items)if(f.itemTypes.contains(i.itemType)&&f.statuses.contains(i.status)&&(in.options.internalReport||!i.internal))items.append(i);
 std::stable_sort(items.begin(),items.end(),[](const auto&a,const auto&b){if(status(a.status)!=status(b.status))return status(a.status)<status(b.status);if(priority(a.priority)!=priority(b.priority))return priority(a.priority)<priority(b.priority);const auto ad=QDate::fromString(a.dueDate,"MM/dd/yyyy"),bd=QDate::fromString(b.dueDate,"MM/dd/yyyy");if(ad.isValid()!=bd.isValid())return ad.isValid();if(ad.isValid()&&ad!=bd)return ad>bd;return false;});
 QString rows,last;for(const auto&i:items){if(i.status!=last){last=i.status;int count=0;for(const auto&v:items)if(v.status==last)++count;rows+="<tr class='group'><td colspan='"+QString::number(in.options.internalReport?13:12)+"'>"+e(last)+" Items ("+QString::number(count)+")</td></tr>";}rows+="<tr class='"+(i.itemType=="Action"?QString("action"):QString("tracker"))+"'><td>"+e(i.number)+"</td><td>"+e(i.name)+"</td><td>"+e(i.identifiedBy)+"</td><td>"+e(i.dateIdentified)+"</td><td>"+e(i.description)+"</td><td>"+e(i.assignedTo)+"</td><td class='priority-"+e(i.priority.toLower())+"'>"+e(i.priority)+"</td><td>"+e(i.status)+"</td><td>"+e(i.dueDate)+"</td><td>"+e(i.lastUpdate)+"</td><td>"+e(i.dateResolved)+"</td><td>"+e(i.comments)+"</td>"+(in.options.internalReport?"<td>"+QString(i.internal?"Y":"N")+"</td>":"")+"</tr>";}
 if(rows.isEmpty())rows="<tr><td colspan='"+QString::number(in.options.internalReport?13:12)+"'>No matching tracker items.</td></tr>";const QString date=in.options.reportingDate.toString("MM/dd/yyyy");const QString internal=in.options.internalReport?"<th>Internal</th>":"";QString fragment="<h1>Item Tracker: "+e(in.projectNumber)+" "+e(in.projectName)+"</h1><table><tr><th>ID</th><th>Item</th><th>Identified By</th><th>Date Identified</th><th>Description</th><th>Assigned To</th><th>Priority</th><th>Status</th><th>Due Date</th><th>Last Updated</th><th>Date Resolved</th><th>Comments</th>"+internal+"</tr>"+rows+"</table><p>Report Date: "+e(date)+"</p><p class='branding'>Created by Project Notes (<a href='https://www.projectnotespro.com'>www.projectnotespro.com</a>)</p>";ReportDocument r;r.workflow=Workflow::TrackerItemsReport;r.emailFragment=fragment;r.htmlDocument="<!doctype html><html><head><meta charset='utf-8'><style>body{font-family:Calibri,Arial,sans-serif;font-size:9pt}h1{color:#fff;background:#1F497D;padding:6px}table{border-collapse:collapse;width:100%}th,td{border:1px solid #808080;padding:3px;vertical-align:top}th,.group{background:#EEECE1;font-weight:bold}.action{background:#F2F2F2}.priority-high{color:#C00000;font-weight:bold}.priority-medium{color:#9C6500;font-weight:bold}.branding{font-size:9pt;color:#000;margin-top:2px}.branding a{color:#0066CC;text-decoration:none}</style></head><body>"+fragment+"</body></html>";QString plain=fragment;plain.remove(QRegularExpression("<[^>]*>"));r.plainText=plain.simplified();r.defaultSubject=in.projectNumber+" "+in.projectName+" - Tracker Items "+date;r.fileStem=in.projectNumber+" Tracker Items"+(in.options.internalReport?" Internal":"");r.pdfLayout=QPageLayout(QPageSize(QPageSize::Letter),QPageLayout::Landscape,QMarginsF(12,12,12,12),QPageLayout::Millimeter);return r;
}
}
